<?php

declare(strict_types=1);

use IntegerNet\SansecWatch\Block\Adminhtml\System\Config\Form\MdnCspLink;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var MdnCspLink $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

$htmlId = $block->getHtmlId();
$escapedHtmlId = $escaper->escapeHtml($htmlId);
$styleString = <<<style
    #row_{$escapedHtmlId} label,
    #row_{$escapedHtmlId} .note,
    #{$escapedHtmlId}_inherit {
        display: none;
    }
style;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styleString, false) ?>

<div style="display: flex; align-items: center;">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-info-icon lucide-info"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
    <span style="margin-left: 1rem">Read more about the directives and their settings at: <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy#directives" target="_blank" rel="noopener noreferrer">MDN Content Security Policy (directives)</a></span>
</div>
