<?php

declare(strict_types=1);

use IntegerNet\SansecWatch\Block\Adminhtml\System\Config\Form\UpdatePolicies;
use Magento\Framework\Escaper;

/** @var UpdatePolicies $block */
/** @var Escaper $escaper */

$htmlId = $block->getHtmlId();
?>
<style>
    #row_<?= $escaper->escapeHtml($htmlId) ?> label,
    #row_<?= $escaper->escapeHtml($htmlId) ?> .note,
    #<?= $escaper->escapeHtml($htmlId) ?>_inherit {
        display: none;
    }
</style>
<script>
    require(['prototype'], function () {
        const button = document.querySelector('#<?= $escaper->escapeJs($htmlId) ?>_button')
        const loading = document.querySelector('#<?= $escaper->escapeJs($htmlId) ?>_loading')
        const messages = document.querySelector('#<?= $escaper->escapeJs($htmlId) ?>_messages')
        const url = new URL('<?= $escaper->escapeJs($block->getAjaxUrl()) ?>')
        url.searchParams.set('isAjax', 'true')

        const showMessages = () => messages.style.display = 'block'
        const hideMessages = () => messages.style.display = 'none'
        const showLoading = () => loading.style.display = 'flex'
        const hideLoading = () => loading.style.display = 'none'
        const enableButton = () => button.disabled = false
        const disableButton = () => button.disabled = true
        const displayMessage = (message, error = false) => {
            messages.innerHTML = error
                ? `<span style="color: red; font-weight: bold">${message}</span>`
                : `<span>${message}</span>`

            showMessages()
        }
        const clearMessages = () => {
            messages.innerHTML = ''
            hideMessages()
        }

        const handleResponse = (response) => {
            hideLoading()
            enableButton()

            if (response.success !== true) {
                displayMessage(response.message, true)
                return
            }

            displayMessage('<?= $escaper->escapeJs(__('Policies updated')) ?>')
            setTimeout(() => window.location.reload(), 250);
        }

        button.addEventListener('click', () => {
            const body = new FormData()
            body.append('form_key', window.FORM_KEY);

            disableButton()
            showLoading()
            clearMessages()

            const options = {
                method: 'POST',
                credentials: 'include',
                body: body,
            }

            fetch(url, options)
                .then(response => response.json())
                .then(handleResponse)
                .catch(error => console.error(error))
        })
    });
</script>
<?= /** @noEscape */ $block->getButtonHtml() ?>

<div id="<?= $escaper->escapeHtmlAttr($htmlId) ?>_loading" style="margin-top: 2rem; display: none; align-items: center;">
    <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <style>
            .spinner_ajPY {
                transform-origin:center;
                animation:spinner_AtaB .75s infinite linear
            }
            @keyframes spinner_AtaB {
                100%{
                    transform:rotate(360deg)
                }
            }
        </style>
        <path d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity=".25"/>
        <path d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z" class="spinner_ajPY"/>
    </svg>
    <span style="margin-left: 1rem">Fetching Policies...</span>
</div>

<div id="<?= $escaper->escapeHtmlAttr($htmlId) ?>_messages" style="margin-top: 2rem; display: none">
</div>
